name: Build
on: push

jobs:
  build:
    name: Build and Upload Artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            target: windows
            bin-path: build/windows/runner/Release
          - os: macos-latest
            target: macos
            bin-path: build/macos/Build/Products/Release
          - os: ubuntu-latest
            target: linux
            bin-path: build/linux/x64/release/bundle
    steps:
    - name: Clone Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: master

    - name: Config Flutter
      run: flutter doctor -v

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Add Support for All Platforms
      run: |
        flutter config --enable-${{ matrix.target }}-desktop -v
        flutter create . -v

    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

    - name: Install Flutter Packages
      run: flutter pub get -v

    - name: Build Executable
      run: flutter build ${{ matrix.target }} -v

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-${{ matrix.target }}
        path: ${{ matrix.bin-path }}
